import { Packager, Package } from './packager.js';

export const coreSymbolsPckg: Package = {
  package: {
    name: '@deep-foundation/core-symbols',
    version: '0.0.0',
    uri: 'deep-foundation/core-symbols',
    type: 'git',
  },
  dependencies: {
    1: {
      name: '@deep-foundation/core',
      version: '0.0.0',
    },
  },
  data: [
    { id: 'Type', package: { dependencyId: 1, containValue: 'Type' } },
    { id: 'Package', package: { dependencyId: 1, containValue: 'Package' } },
    { id: 'Contain', package: { dependencyId: 1, containValue: 'Contain' } },
    { id: 'Value', package: { dependencyId: 1, containValue: 'Value' } },
    { id: 'Promise', package: { dependencyId: 1, containValue: 'Promise' } },
    { id: 'Then', package: { dependencyId: 1, containValue: 'Then' } },
    { id: 'Resolved', package: { dependencyId: 1, containValue: 'Resolved' } },
    { id: 'Rejected', package: { dependencyId: 1, containValue: 'Rejected' } },
    { id: 'Selector', package: { dependencyId: 1, containValue: 'Selector' } },
    { id: 'SelectorInclude', package: { dependencyId: 1, containValue: 'SelectorInclude' } },
    { id: 'SelectorExclude', package: { dependencyId: 1, containValue: 'SelectorExclude' } },
    { id: 'Rule', package: { dependencyId: 1, containValue: 'Rule' } },
    { id: 'RuleSubject', package: { dependencyId: 1, containValue: 'RuleSubject' } },
    { id: 'RuleObject', package: { dependencyId: 1, containValue: 'RuleObject' } },
    { id: 'Rule', package: { dependencyId: 1, containValue: 'Rule' } },
    { id: 'User', package: { dependencyId: 1, containValue: 'User' } },
    { id: 'Operation', package: { dependencyId: 1, containValue: 'Operation' } },
    { id: 'File', package: { dependencyId: 1, containValue: 'File' } },
    { id: 'SyncTextFile', package: { dependencyId: 1, containValue: 'SyncTextFile' } },
    { id: 'ExecutionProvider', package: { dependencyId: 1, containValue: 'ExecutionProvider' } },
    { id: 'IsolationProvider', package: { dependencyId: 1, containValue: 'IsolationProvider' } },
    { id: 'AsyncFile', package: { dependencyId: 1, containValue: 'AsyncFile' } },
    { id: 'Handler', package: { dependencyId: 1, containValue: 'Handler' } },
    { id: 'Tree', package: { dependencyId: 1, containValue: 'Tree' } },
    { id: 'TreeInclude', package: { dependencyId: 1, containValue: 'TreeInclude' } },
    { id: 'PackageNamespace', package: { dependencyId: 1, containValue: 'PackageNamespace' } },
    { id: 'PackageActive', package: { dependencyId: 1, containValue: 'PackageActive' } },
    { id: 'PackageVersion', package: { dependencyId: 1, containValue: 'PackageVersion' } },
    { id: 'HandleOperation', package: { dependencyId: 1, containValue: 'HandleOperation' } },
    { id: 'PromiseResult', package: { dependencyId: 1, containValue: 'PromiseResult' } },
    { id: 'PromiseReason', package: { dependencyId: 1, containValue: 'PromiseReason' } },
    { id: 'Focus', package: { dependencyId: 1, containValue: 'Focus' } },
    { id: 'Query', package: { dependencyId: 1, containValue: 'Query' } },
    { id: 'Space', package: { dependencyId: 1, containValue: 'Space' } },
    { id: 'Join', package: { dependencyId: 1, containValue: 'Join' } },
    { id: 'SelectorTree', package: { dependencyId: 1, containValue: 'SelectorTree' } },
    { id: 'SelectorFilter', package: { dependencyId: 1, containValue: 'SelectorFilter' } },
    { id: 'Schedule', package: { dependencyId: 1, containValue: 'Schedule' } },
    { id: 'Router', package: { dependencyId: 1, containValue: 'Router' } },
    { id: 'Supports', package: { dependencyId: 1, containValue: 'Supports' } },
    { id: 'PackageInstall', package: { dependencyId: 1, containValue: 'PackageInstall' } },
    { id: 'PackagePublish', package: { dependencyId: 1, containValue: 'PackagePublish' } },
    { id: 'Active', package: { dependencyId: 1, containValue: 'Active' } },
    { id: 'PromiseOut', package: { dependencyId: 1, containValue: 'PromiseOut' } },
    { id: 'PackageQuery', package: { dependencyId: 1, containValue: 'PackageQuery' } },
    { id: 'Port', package: { dependencyId: 1, containValue: 'Port' } },
    { id: 'Route', package: { dependencyId: 1, containValue: 'Route' } },
    { id: 'RouterListening', package: { dependencyId: 1, containValue: 'RouterListening' } },
    { id: 'RouterStringUse', package: { dependencyId: 1, containValue: 'RouterStringUse' } },
    { id: 'Authorization', package: { dependencyId: 1, containValue: 'Authorization' } },
    { id: 'GeneratedFrom', package: { dependencyId: 1, containValue: 'GeneratedFrom' } },
    { id: 'Symbol', package: { dependencyId: 1, containValue: 'Symbol' } },

    { id: 'TypeSymbol', type: 'Symbol', from: 'Type', to: 'Type', value: { value: '⭐️' } },
    { id: 'PackageSymbol', type: 'Symbol', from: 'Package', to: 'Package', value: { value: '📦' } },
    { id: 'ContainSymbol', type: 'Symbol', from: 'Contain', to: 'Contain', value: { value: '🗂' } },
    { id: 'ValueSymbol', type: 'Symbol', from: 'Value', to: 'Value', value: { value: '📎' } },
    { id: 'PromiseSymbol', type: 'Symbol', from: 'Promise', to: 'Promise', value: { value: '⏳' } },
    { id: 'ThenSymbol', type: 'Symbol', from: 'Then', to: 'Then', value: { value: '🔗' } },
    { id: 'ResolvedSymbol', type: 'Symbol', from: 'Resolved', to: 'Resolved', value: { value: '🟢' } },
    { id: 'RejectedSymbol', type: 'Symbol', from: 'Rejected', to: 'Rejected', value: { value: '🔴' } },
    { id: 'SelectorSymbol', type: 'Symbol', from: 'Selector', to: 'Selector', value: { value: '🪢' } },
    { id: 'SelectorIncludeSymbol', type: 'Symbol', from: 'SelectorInclude', to: 'SelectorInclude', value: { value: '🪡' } },
    { id: 'SelectorExcludeSymbol', type: 'Symbol', from: 'SelectorExclude', to: 'SelectorExclude', value: { value: '🪡' } },
    { id: 'RuleSymbol', type: 'Symbol', from: 'Rule', to: 'Rule', value: { value: '📜' } },
    { id: 'RuleSubjectSymbol', type: 'Symbol', from: 'RuleSubject', to: 'RuleSubject', value: { value: '👤' } },
    { id: 'RuleObjectSymbol', type: 'Symbol', from: 'RuleObject', to: 'RuleObject', value: { value: '🍏' } },
    { id: 'RuleActionSymbol', type: 'Symbol', from: 'Rule', to: 'Rule', value: { value: '🔥' } },
    { id: 'UserSymbol', type: 'Symbol', from: 'User', to: 'User', value: { value: '👤' } },
    { id: 'OperationSymbol', type: 'Symbol', from: 'Operation', to: 'Operation', value: { value: '🔥' } },
    { id: 'FileSymbol', type: 'Symbol', from: 'File', to: 'File', value: { value: '💾' } },
    { id: 'SyncTextFileSymbol', type: 'Symbol', from: 'SyncTextFile', to: 'SyncTextFile', value: { value: '📄' } },
    { id: 'ExecutionProviderSymbol', type: 'Symbol', from: 'ExecutionProvider', to: 'ExecutionProvider', value: { value: '🔌' } },
    { id: 'IsolationProviderSymbol', type: 'Symbol', from: 'IsolationProvider', to: 'IsolationProvider', value: { value: '📡' } },
    { id: 'AsyncFileSymbol', type: 'Symbol', from: 'AsyncFile', to: 'AsyncFile', value: { value: '💽' } },
    { id: 'HandlerSymbol', type: 'Symbol', from: 'Handler', to: 'Handler', value: { value: '💡' } },
    { id: 'TreeSymbol', type: 'Symbol', from: 'Tree', to: 'Tree', value: { value: '🌲' } },
    { id: 'TreeIncludeSymbol', type: 'Symbol', from: 'TreeInclude', to: 'TreeInclude', value: { value: '🌿' } },
    { id: 'PackageNamespaceSymbol', type: 'Symbol', from: 'PackageNamespace', to: 'PackageNamespace', value: { value: '🎁' } },
    { id: 'PackageActiveSymbol', type: 'Symbol', from: 'PackageActive', to: 'PackageActive', value: { value: '📯' } },
    { id: 'PackageVersionSymbol', type: 'Symbol', from: 'PackageVersion', to: 'PackageVersion', value: { value: '🏷' } },
    { id: 'HandleOperationSymbol', type: 'Symbol', from: 'HandleOperation', to: 'HandleOperation', value: { value: '🛠' } },
    { id: 'PromiseResultSymbol', type: 'Symbol', from: 'PromiseResult', to: 'PromiseResult', value: { value: '🔖' } },
    { id: 'PromiseReasonSymbol', type: 'Symbol', from: 'PromiseReason', to: 'PromiseReason', value: { value: '🧲' } },
    { id: 'FocusSymbol', type: 'Symbol', from: 'Focus', to: 'Focus', value: { value: '📌' } },
    { id: 'QuerySymbol', type: 'Symbol', from: 'Query', to: 'Query', value: { value: '🔎' } },
    { id: 'SpaceSymbol', type: 'Symbol', from: 'Space', to: 'Space', value: { value: '🔮' } },
    { id: 'JoinSymbol', type: 'Symbol', from: 'Join', to: 'Join', value: { value: '🤝' } },
    { id: 'SelectorTreeSymbol', type: 'Symbol', from: 'SelectorTree', to: 'SelectorTree', value: { value: '🌲' } },
    { id: 'SelectorFilterSymbol', type: 'Symbol', from: 'SelectorFilter', to: 'SelectorFilter', value: { value: '🔎' } },
    { id: 'ScheduleSymbol', type: 'Symbol', from: 'Schedule', to: 'Schedule', value: { value: '⏲' } },
    { id: 'RouterSymbol', type: 'Symbol', from: 'Router', to: 'Router', value: { value: '🚦' } },
    { id: 'SupportsSymbol', type: 'Symbol', from: 'Supports', to: 'Supports', value: { value: '🔋' } },
    { id: 'PackageInstallSymbol', type: 'Symbol', from: 'PackageInstall', to: 'PackageInstall', value: { value: '📥' } },
    { id: 'PackagePublishSymbol', type: 'Symbol', from: 'PackagePublish', to: 'PackagePublish', value: { value: '📤' } },
    { id: 'ActiveSymbol', type: 'Symbol', from: 'Active', to: 'Active', value: { value: '💡' } },
    { id: 'PromiseOutSymbol', type: 'Symbol', from: 'PromiseOut', to: 'PromiseOut', value: { value: '🧷' } },
    { id: 'PackageQuerySymbol', type: 'Symbol', from: 'PackageQuery', to: 'PackageQuery', value: { value: '🏷' } },
    { id: 'PortSymbol', type: 'Symbol', from: 'Port', to: 'Port', value: { value: '🗜' } },
    { id: 'RouteSymbol', type: 'Symbol', from: 'Route', to: 'Route', value: { value: '🚏' } },
    { id: 'RouterListeningSymbol', type: 'Symbol', from: 'RouterListening', to: 'RouterListening', value: { value: '🔗' } },
    { id: 'RouterStringUseSymbol', type: 'Symbol', from: 'RouterStringUse', to: 'RouterStringUse', value: { value: '🔗' } },
    { id: 'AuthorizationSymbol', type: 'Symbol', from: 'Authorization', to: 'Authorization', value: { value: '🔑' } },
    { id: 'GeneratedFromSymbol', type: 'Symbol', from: 'GeneratedFrom', to: 'GeneratedFrom', value: { value: '🏗' } },
    { id: 'SymbolSymbol', type: 'Symbol', from: 'Symbol', to: 'Symbol', value: { value: '🙂' } },
  ],
  errors: [],
};